"""Routes tagged "evidence"."""
from __future__ import annotations

import json

from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import PlainTextResponse, Response

from tracex_api import audit, db
from tracex_api.auth import User, current_user, export_user, require_supervisor
from tracex_api.engine import correlate, evidentiary, scoring, views
from tracex_api.engine.dataset import current

router = APIRouter(tags=["evidence"])


def _entity(entity_id: str):
    ds = current()
    if entity_id not in ds.persons:
        raise HTTPException(status_code=404, detail="no such entity in the graph")
    return ds


@router.get("/evidence/counterfactual/{entity_id}", summary="Counterfactual")
def counterfactual(entity_id: str, user: User = Depends(current_user)):
    ds = _entity(entity_id)
    audit.record(user.username, "evidence.counterfactual", "entity", entity_id)
    return evidentiary.counterfactual(ds, entity_id)


@router.get("/evidence/exculpatory/{entity_id}", summary="Exculpatory")
def exculpatory(entity_id: str, user: User = Depends(current_user)):
    ds = _entity(entity_id)
    audit.record(user.username, "evidence.exculpatory", "entity", entity_id)
    return evidentiary.exculpatory(ds, entity_id)


def _case_code(case_id: int | None) -> str | None:
    if case_id is None:
        return None
    row = db.query_one("SELECT case_code FROM cases WHERE id = ?", (case_id,))
    if not row:
        raise HTTPException(status_code=404, detail="no such case")
    return row["case_code"]


@router.get("/evidence/bsa-certificate", summary="Bsa Certificate")
def bsa_certificate(case_id: int | None = Query(None), entity_id: str | None = Query(None), fmt: str = Query("json"),
                    user: User = Depends(export_user)):
    code = _case_code(case_id)
    if entity_id:
        _entity(entity_id)
    result = evidentiary.certificate(code, entity_id)
    audit.record(user.username, "evidence.bsa_certificate", "case" if case_id is not None else "entity", case_id if case_id is not None else entity_id)
    if fmt == "text":
        return PlainTextResponse(result["text"])
    if fmt == "pdf":
        return Response(evidentiary.simple_pdf(result["text"], "BSA s.63 certificate"), media_type="application/pdf",
                        headers={"Content-Disposition": 'attachment; filename="bsa_s63_certificate.pdf"'})
    return result


@router.get("/evidence/package", summary="Evidence Package")
def evidence_package(case_id: int | None = Query(None), entity_id: str | None = Query(None), fmt: str = Query("json"),
                     user: User = Depends(export_user)):
    """Everything a reviewer needs to re-check a finding, in one export. Supervisor only, audited."""
    require_supervisor(user)
    if case_id is None and entity_id is None:
        raise HTTPException(status_code=422, detail="give case_id or entity_id")
    ds = current()
    code = _case_code(case_id)
    if case_id is not None:
        entity_ids = [r["entity_id"] for r in db.query("SELECT entity_id FROM case_entities WHERE case_id = ? ORDER BY rowid", (case_id,))]
        notes = [dict(r) for r in db.query("SELECT body, author, created_at FROM case_notes WHERE case_id = ? ORDER BY id", (case_id,))]
    else:
        _entity(entity_id)
        entity_ids, notes = [entity_id], []
    scores = scoring.scores(ds)
    subjects = []
    for pid in entity_ids:
        if pid not in ds.persons:
            continue
        p = ds.persons[pid]
        subjects.append({
            "entity_id": pid, "name": p.name, "risk": {k: scores[pid][k] for k in ("risk_score", "band", "model", "top_factors")},
            "identifiers": views.profile(ds, pid)["identifiers"],
            "call_to_debit_links": [l for l in correlate.call_to_debit(ds) if l["person"] == pid],
            "fanout_links": [l for l in correlate.fanout(ds) if l["person"] == pid],
            "exculpatory": evidentiary.exculpatory(ds, pid),
            "counterfactual": evidentiary.counterfactual(ds, pid),
        })
    cert = evidentiary.certificate(code, entity_id)
    package = {"case_code": code, "entity_id": entity_id, "generated_by": user.username, "certificate": cert["certificate"],
               "subjects": subjects, "case_notes": notes, "disposition_note": "Scores rank the review queue; they are not findings."}
    audit.record(user.username, "evidence.package.export", "case" if case_id is not None else "entity", case_id if case_id is not None else entity_id, f"fmt={fmt}")
    if fmt in ("text", "pdf"):
        lines = [f"TRACE-X EVIDENCE PACKAGE — {code or entity_id}", f"Generated by {user.username}", ""]
        for s in subjects:
            lines += [f"SUBJECT {s['entity_id']} · {s['name']}", f"  Risk: {s['risk']['risk_score']:.4f} ({s['risk']['band']}, {s['risk']['model']})"]
            lines += [f"  Factor {t['feature']} = {t['value']} ({t['direction']} {t['shap']:+.4f})" for t in s["risk"]["top_factors"]]
            lines += [f"  Call→debit {l['call_rec_id']} → {l['debit_rec_id']}: Rs {l['amount']:,} after {l['latency_s']}s" for l in s["call_to_debit_links"][:20]]
            ex = s["exculpatory"]
            lines += [f"  Exculpatory adjustment: {ex['original_risk_score']} → {ex['adjusted_risk_score']} ({', '.join(ex['applied']) or 'none applied'})", ""]
        if notes:
            lines += ["CASE NOTES"] + [f"  [{n['created_at']}] {n['author']}: {n['body']}" for n in notes] + [""]
        lines += ["", cert["text"]]
        text = "\n".join(lines)
        if fmt == "text":
            return PlainTextResponse(text)
        return Response(evidentiary.simple_pdf(text, f"Evidence package {code or entity_id}"), media_type="application/pdf",
                        headers={"Content-Disposition": f'attachment; filename="evidence_package_{code or entity_id}.pdf"'})
    return package
