"""Compliance programme: a catalogue of controls, each re-evaluated against the running deployment.

Controls a verifier can check are recomputed on every read. Controls nothing can verify are reported
as unclaimed ('manual') and score zero — an attestation records a person's claim in the audit log but
never flips a status, because a status must be a measurement.
"""
from __future__ import annotations

import json
import os
from collections import Counter
from datetime import datetime, timedelta, timezone
from pathlib import Path

from tracex_api import audit, db, evidence
from tracex_api.auth import USERS

SEED = Path(__file__).resolve().parents[1] / "seed_data"
REPO = Path(__file__).resolve().parents[3]
STATUS_ORDER = {"gap": 0, "partial": 1, "manual": 2, "not_applicable": 3, "satisfied": 4}
SCORE = {"satisfied": 1.0, "partial": 0.5, "gap": 0.0, "manual": 0.0}
FRAMEWORK = "TRACE-X Compliance Program"
SCOPE = ("The TRACE-X multi-source investigative analytics application (CDR/IPDR, banking, social media and ALPR), its SQLite system of record "
         "with the in-process knowledge graph derived from it, and the evidence lifecycle from ingest through analysis to certified export.")
OUT_OF_SCOPE = ("The deploying agency's corporate estate — email, end-user devices, network perimeter, physical premises and HR processes. "
                "Those controls are listed with owner 'agency' so the boundary is auditable, never silently omitted.")
ATTESTATION = ("Generated by inspecting this running deployment. Controls marked 'manual' are unclaimed, not passing, and score zero. "
               "This is a self-assessment and is not an independent assurance opinion.")
HOW_SCORED = ("satisfied=1.0, partial=0.5, gap=0.0, manual=0.0. Controls marked not_applicable are excluded from the denominator, with a stated reason. "
              "Unclaimed organizational controls score zero on purpose: a control nobody has evidenced is not a control that is working.")
PRIVILEGED = ["action.withdraw", "action.freeze_request", "action.sar_draft", "evidence.package.export", "integrity.drill", "integrity.restore"]


def _catalogue() -> list[dict]:
    return json.loads((SEED / "catalog" / "compliance_controls.json").read_text(encoding="utf-8"))["controls"]


def _logged(action: str, within_days: int = 365) -> list:
    since = (datetime.now(timezone.utc) - timedelta(days=within_days)).isoformat()
    return db.query("SELECT actor, ts FROM audit WHERE action = ? AND ts >= ? ORDER BY id DESC", (action, since))


def _verify(control: dict) -> dict:
    c = dict(control)
    cid = c["id"]

    def set_(status, detail, observations):
        c.update(status=status, detail=detail, observations=observations)

    if cid == "CTL-ACC-001":
        roles = sorted({u["role"] for u in USERS.values()})
        set_("satisfied", f"{len(USERS)} users provisioned, every one holding a defined role; {len(PRIVILEGED)} actions are restricted to supervisors.",
             [f"roles in use: {', '.join(roles)}", f"privileged actions: {', '.join(PRIVILEGED)}",
              "Access is granted by provisioning a user; an unprovisioned identity is rejected at the door with 401."])
    elif cid == "CTL-ACC-003":
        sups = sorted(n for n, u in USERS.items() if u["role"] == "supervisor")
        set_("satisfied" if len(sups) < len(USERS) else "partial", f"{len(sups)} of {len(USERS)} users hold supervisor rights; the rest operate unprivileged.",
             [f"supervisors: {', '.join(sups)}"])
    elif cid == "CTL-ACC-004":
        rows = _logged("access.review")
        if rows:
            set_("satisfied", f"Access review logged {len(rows)} time(s) in the last 12 months; most recent by {rows[0]['actor']} at {rows[0]['ts']}.",
                 ["Evidenced by audit action 'access.review'."])
    elif cid == "CTL-DAT-005":
        batches = evidence.batches()
        by_source = Counter()
        count_batches = Counter()
        for b in batches:
            by_source[b["source_type"]] += b["records"]
            count_batches[b["source_type"]] += 1
        set_("satisfied", f"Live inventory across {len(by_source)} source type(s), {sum(by_source.values())} records total — derived from storage, not maintained by hand.",
             [f"{s}: {n} records across {count_batches[s]} batch(es)" for s, n in sorted(by_source.items())]
             + ["Every row records its source file, batch, ingest time and ingesting user."])
    elif cid == "CTL-DAT-006":
        classes = sorted({b["source_type"] for b in evidence.batches()})
        set_("satisfied", "Every record is classified by source type at ingest and carries that label for its whole life.",
             [f"classes present: {', '.join(classes)}", "The label drives handling: source type selects the parser, the graph projection, and which analyses may read the row."])
    elif cid == "CTL-DAT-009":
        results = [evidence.verify_batch(b) for b in evidence.batches()]
        total = sum(r["records"] for r in results)
        broken = [r for r in results if not r["intact"]]
        if broken:
            set_("gap", f"{len(broken)} of {len(results)} batch(es) fail verification — stored evidence no longer matches what was recorded at ingest.",
                 [f"{r['source_type']} {r['batch_id']}: first breach {r['first_breach']['kind']} at {r['first_breach'].get('record_id') or 'seq ' + str(r['first_breach']['seq'])}" for r in broken]
                 + ["Restore the altered record (POST /integrity/restore) and re-verify."])
        else:
            set_("satisfied", f"All {total} records across {len(results)} batch(es) re-hashed and every chain re-walked; no discrepancy.",
                 ["This is a full re-hash of stored payloads, not a link-only check — the latter would miss an edit made directly in the database.",
                  "The same check is exposed at /integrity/verify, and /integrity/drill will break it on demand so the verifier can be watched catching it."])
    elif cid == "CTL-DAT-010":
        n = db.query_one("SELECT COUNT(*) AS n FROM audit WHERE action LIKE '%export%' OR action LIKE 'evidence.%'")["n"]
        c["detail"] = "Evidence leaves the system only through the export path, which is supervisor-gated, hash-certified and audited."
        c["observations"] = [f"{n} export-related audit entries recorded."] + control["observations"][1:]
    elif cid == "CTL-MON-002":
        total = db.query_one("SELECT COUNT(*) AS n FROM audit")["n"]
        actors = db.query_one("SELECT COUNT(DISTINCT actor) AS n FROM audit")["n"]
        top = db.query("SELECT action, COUNT(*) AS n FROM audit GROUP BY action ORDER BY n DESC LIMIT 8")
        set_("satisfied" if total else "gap", f"{total} audit entries from {actors} distinct actor(s), across {len(top)}+ action types.",
             [f"{r['action']}: {r['n']}" for r in top] + ["The actor is derived from the request identity, never accepted as a client-supplied field — an audit log the caller can forge is decoration."])
    elif cid == "CTL-MON-011":
        targets = db.query_one("SELECT COUNT(*) AS n FROM targets")["n"]
        campaigns = len(db.doc_list("campaigns"))
        if targets and campaigns:
            set_("satisfied", f"{targets} watchlist target(s) and {campaigns} campaign signature(s) are held and applied across views.", control["observations"])
        else:
            c["detail"] = f"The watchlist and campaign-signature mechanisms exist; {targets} target(s) and {campaigns} signature(s) are held."
    elif cid == "CTL-DR-005":
        rows = _logged("dr.test")
        if rows:
            set_("satisfied", f"Recovery exercise logged {len(rows)} time(s) in the last 12 months; most recent at {rows[0]['ts']}.", ["Evidenced by audit action 'dr.test'."])
    elif cid == "CTL-RSK-004":
        rows = _logged("risk.assessment")
        if rows:
            set_("satisfied", f"Risk assessment logged {len(rows)} time(s) in the last 12 months.", ["Evidenced by audit action 'risk.assessment'."])
    elif cid == "CTL-INF-018":
        if os.environ.get("TRACEX_SECRET"):
            set_("satisfied", "Session tokens are signed with a deployment-specific secret supplied from the environment.", ["TRACEX_SECRET is set."])
        else:
            set_("gap", "Session tokens are signed with the shipped demo secret.",
                 ["Reported as a gap rather than hidden: this is exactly the finding a compliance report exists to surface.",
                  "Set TRACEX_SECRET (and move the SQLite file to an access-controlled volume) before any real deployment."])
    elif cid == "CTL-ORG-037":
        tests = list((REPO / "api" / "tests").glob("*.py"))
        if tests:
            set_("partial", f"{len(tests)} automated test module(s) found, including a parity suite against the original deployment's responses.",
                 ["Tests exist and run locally; wiring them into CI with a required status check is the remaining step."])
    elif cid == "CTL-RSK-008":
        manifests = [p for p in [REPO / "api" / "requirements.txt", REPO / "frontend" / "package-lock.json"] if p.exists()]
        if manifests:
            set_("partial", "Dependencies are pinned in manifests, but nothing monitors them for new advisories.",
                 [f"manifests: {', '.join(str(m.relative_to(REPO)) for m in manifests)}", "Add dependency auditing (pip-audit, npm audit) to CI."])
    elif cid == "CTL-INF-015":
        c["observations"] = ["The tamper drill is enabled (supervisor-only), so this instance must be treated as non-production.",
                             "Disable the drill route and reseed from real evidence for any production deployment."]
    return c


def controls(domain: str | None = None, status: str | None = None, owner: str | None = None) -> dict:
    evaluated = [_verify(c) for c in _catalogue()]
    evaluated.sort(key=lambda c: (STATUS_ORDER[c["status"]], c["id"]))
    domains = sorted({c["domain"] for c in evaluated})
    filtered = [c for c in evaluated if (domain is None or c["domain"] == domain) and (status is None or c["status"] == status)
                and (owner is None or c["owner"] == owner)]
    return {"generated_at": datetime.now(timezone.utc).isoformat(), "domains": domains, "filters": {"domain": domain, "status": status, "owner": owner},
            "count": len(filtered), "total_controls": len(evaluated), "controls": filtered}


def control(control_id: str) -> dict | None:
    return next((_verify(c) for c in _catalogue() if c["id"] == control_id), None)


def _readiness(items: list[dict]) -> float | None:
    scored = [c for c in items if c["status"] != "not_applicable"]
    if not scored:
        return None
    return round(sum(SCORE[c["status"]] for c in scored) / len(scored) * 100, 1)


def program() -> dict:
    items = controls()["controls"]
    counts = {s: sum(1 for c in items if c["status"] == s) for s in STATUS_ORDER}
    domains = []
    for d in sorted({c["domain"] for c in items}):
        dc = [c for c in items if c["domain"] == d]
        domains.append({"domain": d, "total": len(dc), "counts": {s: sum(1 for c in dc if c["status"] == s) for s in STATUS_ORDER}, "readiness": _readiness(dc)})
    readiness = _readiness(items)
    return {
        "framework": FRAMEWORK, "generated_at": datetime.now(timezone.utc).isoformat(), "scope": SCOPE, "out_of_scope": OUT_OF_SCOPE,
        "readiness": round(readiness) if readiness is not None and readiness.is_integer() else readiness,
        "scored_controls": sum(1 for c in items if c["status"] != "not_applicable"), "total_controls": len(items), "counts": counts, "domains": domains,
        "attestation": ATTESTATION,
        "open_findings": [c for c in items if c["status"] == "gap"],
        "unclaimed": [{k: c[k] for k in ("id", "domain", "name", "detail")} for c in items if c["status"] == "manual"],
        "how_scored": HOW_SCORED,
    }


def attest(control_id: str, note: str, user) -> dict:
    c = control(control_id)
    if c is None:
        return None
    entry_id = audit.record(user.username, "compliance.attest", "control", control_id, note)
    record = {"id": entry_id, "control_id": control_id, "control_name": c["name"], "note": note, "attested_by": user.username,
              "attested_at": db.now_iso(), "status_at_attestation": c["status"],
              "effect": "Recorded in the audit log. The control's status still comes from its verifier; an attestation never flips it."}
    db.doc_put("attestations", entry_id, record)
    return record


def attestations() -> dict:
    items = sorted(db.doc_list("attestations"), key=lambda a: a["attested_at"], reverse=True)
    return {"count": len(items), "attestations": items}


def report_text(user: str) -> str:
    p = program()
    items = controls()["controls"]
    out = [FRAMEWORK, "=" * len(FRAMEWORK), "", f"Generated : {p['generated_at']}", f"By        : {user}",
           f"Readiness : {float(p['readiness']):.1f}% over {p['scored_controls']} scored controls", "", "SCOPE", f"  {p['scope']}", "",
           "OUT OF SCOPE", f"  {p['out_of_scope']}", "", "POSTURE"]
    out += [f"  {s:<16} {n}" for s, n in p["counts"].items()]
    out += ["", "BY DOMAIN"]
    for d in p["domains"]:
        ready = "n/a" if d["readiness"] is None else f"{d['readiness']:.1f}%"
        out.append(f"  {d['domain']:<40} {d['total']:>2} controls {ready:>8}")
    out += ["", "CONTROLS (worst first)", ""]
    for c in items:
        out += [f"  [{c['status'].upper()}] {c['id']}  {c['name']}", f"      owner  : {c['owner']}", f"      finding: {c['detail']}"]
        out += [f"        - {o}" for o in c["observations"]]
        out.append("")
    out += ["", ATTESTATION, ""]
    return "\n".join(out)
